language: node_js

jobs:
  fast_finish: true

  include:
    - stage: Lint
      env: SCRIPT=lint
      node_js: 'stable'

    - &osx
      stage: Test
      os: 'osx'
      env: SCRIPT=test
      node_js: 'stable'
    - <<: *osx
      node_js: 'lts/*'
    - <<: *osx
      node_js: 6

    - &linux
      stage: Test
      env: SCRIPT=test
      node_js: 'stable'
    - <<: *linux
      node_js: 'lts/*'
    - <<: *linux
      node_js: 6

    - &windows
      stage: Test
      os: 'windows'
      env: SCRIPT=test
      node_js: 'latest'
    - <<: *windows
      node_js: 'lts'
    - <<: *windows
      node_js: 6

install:
  - if [[ "$TRAVIS_OS_NAME" != 'windows' ]]; then
      npm i -g npm@latest;
    fi
  - npm i

script: npm run $SCRIPT

after_success:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      npm i codecov;
      $(npm bin)/codecov;
    fi

notifications:
  email: false
